# Variables
@baseUrl = http://localhost:3333


#Health check
# @name healthCheck
GET {{baseUrl}}/health


###


# Get Rooms
# @name getRooms
GET {{baseUrl}}/rooms


###


# Create Room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Sala teste",
    "description": "Isso é uma sala teste"
}


###


@roomId = {{createRoom.response.body.$.roomId}}


###


# Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions


###


# Create Question
# @name createQuestion
POST {{baseUrl}}/rooms/ce00d019-c023-4caf-8c1f-2c5fd596d96a/questions
Content-Type: application/json

{
    "question": "O que é React?"
}